# Form implementation generated from reading ui file 'c:\Users\hp\Documents\CS_Undergrad\Semester_3\DATABASE\bd_final_project\DairyPro\DB_ConnectionsFiles\customer_sameer\26 Customer Order Button.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(512, 649)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.booksTableWidget = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.booksTableWidget.setGeometry(QtCore.QRect(30, 180, 441, 191))
        self.booksTableWidget.setStyleSheet("QTableWidget {\n"
"    background-color: rgb(169, 192, 255);\n"
"   alternate-background-color: #e0e0e0;\n"
"   selection-background-color: #4CAF50;\n"
"    border:  rgb(0, 0, 127);; /* Border color around the table */\n"
"    margin: 5px; /* Set the margin size */\n"
"    font: 8pt \"Comic Sans MS\";\n"
"    color: rgb(0, 0, 127);\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    font: 8pt \"Comic Sans MS\";\n"
"    color: rgb(0, 0, 127);\n"
"    \n"
"}\n"
"\n"
"\n"
"QHeaderView::section {\n"
"    background-color:  rgb(169, 192, 255); /* Header background color */\n"
"    color: rgb(0, 0, 127); /* Header text color */\n"
"    padding: 4px; /* Header padding */\n"
"    font: 8pt \"Comic Sans MS\";\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"    background-color: rgb(0, 0, 127) /* Background color for selected items */\n"
"    color: white; /* Text color for selected items */\n"
"}\n"
"")
        self.booksTableWidget.setObjectName("booksTableWidget")
        self.booksTableWidget.setColumnCount(5)
        self.booksTableWidget.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.booksTableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.booksTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.booksTableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.booksTableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.booksTableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.booksTableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.booksTableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.booksTableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.booksTableWidget.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.booksTableWidget.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.booksTableWidget.setItem(0, 4, item)
        self.deleteButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.deleteButton.setGeometry(QtCore.QRect(220, 430, 121, 31))
        self.deleteButton.setStyleSheet("background-color: rgb(174, 209, 255);\n"
"font: 10pt \"Comic Sans MS\";\n"
"color: #00007f;\n"
"border-style: outset;\n"
"border-width: 3px;\n"
"border-radius: 5px;\n"
"border-color: #00007f;\n"
"")
        self.deleteButton.setObjectName("deleteButton")
        self.searched = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.searched.setGeometry(QtCore.QRect(30, 20, 441, 141))
        self.searched.setStyleSheet("font: 10pt \"Comic Sans MS\";\n"
"border-color: rgb(0, 0, 127);\n"
"border-width: 10px;\n"
"color: rgb(0, 0, 127);")
        self.searched.setObjectName("searched")
        self.searchButton = QtWidgets.QPushButton(parent=self.searched)
        self.searchButton.setGeometry(QtCore.QRect(280, 100, 121, 31))
        self.searchButton.setStyleSheet("background-color: rgb(174, 209, 255);\n"
"font: 10pt \"Comic Sans MS\";\n"
"color: #00007f;\n"
"border-style: outset;\n"
"border-width: 3px;\n"
"border-radius: 5px;\n"
"border-color: #00007f;\n"
"")
        self.searchButton.setObjectName("searchButton")
        self.label = QtWidgets.QLabel(parent=self.searched)
        self.label.setGeometry(QtCore.QRect(20, -10, 90, 129))
        self.label.setText("")
        self.label.setObjectName("label")
        self.prodName = QtWidgets.QLineEdit(parent=self.searched)
        self.prodName.setGeometry(QtCore.QRect(138, 50, 241, 20))
        self.prodName.setStyleSheet("background-color: rgb(169, 192, 255);\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 5px;\n"
"border-color: #00007f;")
        self.prodName.setObjectName("prodName")
        self.label_2 = QtWidgets.QLabel(parent=self.searched)
        self.label_2.setGeometry(QtCore.QRect(30, 50, 131, 16))
        self.label_2.setObjectName("label_2")
        self.closeButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.closeButton.setGeometry(QtCore.QRect(350, 430, 121, 31))
        self.closeButton.setStyleSheet("background-color: rgb(174, 209, 255);\n"
"font: 10pt \"Comic Sans MS\";\n"
"color: #00007f;\n"
"border-style: outset;\n"
"border-width: 3px;\n"
"border-radius: 5px;\n"
"border-color: #00007f;\n"
"")
        self.closeButton.setObjectName("closeButton")
        self.viewButton_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.viewButton_2.setGeometry(QtCore.QRect(350, 390, 121, 31))
        self.viewButton_2.setStyleSheet("background-color: rgb(174, 209, 255);\n"
"font: 10pt \"Comic Sans MS\";\n"
"color: #00007f;\n"
"border-style: outset;\n"
"border-width: 3px;\n"
"border-radius: 5px;\n"
"border-color: #00007f;\n"
"")
        self.viewButton_2.setObjectName("viewButton_2")
        self.viewButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.viewButton.setGeometry(QtCore.QRect(220, 390, 121, 31))
        self.viewButton.setStyleSheet("background-color: rgb(174, 209, 255);\n"
"font: 10pt \"Comic Sans MS\";\n"
"color: #00007f;\n"
"border-style: outset;\n"
"border-width: 3px;\n"
"border-radius: 5px;\n"
"border-color: #00007f;\n"
"")
        self.viewButton.setObjectName("viewButton")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(-30, -20, 921, 681))
        self.label_4.setAutoFillBackground(False)
        self.label_4.setStyleSheet("\n"
"\n"
"background-color: rgb(207, 232, 255);\n"
"")
        self.label_4.setFrameShape(QtWidgets.QFrame.Shape.Panel)
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_4.raise_()
        self.booksTableWidget.raise_()
        self.deleteButton.raise_()
        self.searched.raise_()
        self.closeButton.raise_()
        self.viewButton_2.raise_()
        self.viewButton.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 512, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        item = self.booksTableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.booksTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Product ID"))
        item = self.booksTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Product Name"))
        item = self.booksTableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Category ID"))
        item = self.booksTableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Price"))
        item = self.booksTableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Continuity Status"))
        __sortingEnabled = self.booksTableWidget.isSortingEnabled()
        self.booksTableWidget.setSortingEnabled(False)
        item = self.booksTableWidget.item(0, 0)
        item.setText(_translate("MainWindow", "0001"))
        item = self.booksTableWidget.item(0, 1)
        item.setText(_translate("MainWindow", "011245"))
        item = self.booksTableWidget.item(0, 2)
        item.setText(_translate("MainWindow", "2005"))
        item = self.booksTableWidget.item(0, 3)
        item.setText(_translate("MainWindow", "1/1/2000"))
        item = self.booksTableWidget.item(0, 4)
        item.setText(_translate("MainWindow", "2"))
        self.booksTableWidget.setSortingEnabled(__sortingEnabled)
        self.deleteButton.setText(_translate("MainWindow", "Delete"))
        self.searched.setTitle(_translate("MainWindow", "Search"))
        self.searchButton.setText(_translate("MainWindow", "Search"))
        self.prodName.setText(_translate("MainWindow", "Nido"))
        self.label_2.setText(_translate("MainWindow", "Product Name:"))
        self.closeButton.setText(_translate("MainWindow", "Close"))
        self.viewButton_2.setText(_translate("MainWindow", "Place Order"))
        self.viewButton.setText(_translate("MainWindow", "View"))
