# Form implementation generated from reading ui file 'c:\Users\hp\Documents\CS_Undergrad\Semester_3\DATABASE\bd_final_project\DairyPro\Code-Connection\Screens\1 User Type.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(876, 689)
        MainWindow.setStyleSheet("QPushButton,\n"
"QPushButton:focus {\n"
" color: rgb(255, 255, 255); background-color: #8360aa;  border: 3px solid #8360aa;}\n"
"\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(290, 150, 271, 411))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.loginAdmin = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.loginAdmin.setStyleSheet("QPushButton:hover,\n"
"QPushButton:focus {\n"
"    \n"
"  color: rgb(255, 255, 255);\n"
"  background-color: #8360aa;\n"
"  border: 3px solid #8360aa;\n"
"}")
        self.loginAdmin.setObjectName("loginAdmin")
        self.verticalLayout.addWidget(self.loginAdmin)
        self.loginDistributor = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.loginDistributor.setStyleSheet("QPushButton:hover,\n"
"QPushButton:focus {\n"
"    \n"
"  color: rgb(255, 255, 255);\n"
"  background-color: #8360aa;\n"
"  border: 3px solid #8360aa;\n"
"}")
        self.loginDistributor.setObjectName("loginDistributor")
        self.verticalLayout.addWidget(self.loginDistributor)
        self.loginCustomer = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.loginCustomer.setStyleSheet("QPushButton:hover,\n"
"QPushButton:focus {\n"
"    \n"
"  color: rgb(255, 255, 255);\n"
"  background-color: #8360aa;\n"
"  border: 3px solid #8360aa;\n"
"}")
        self.loginCustomer.setObjectName("loginCustomer")
        self.verticalLayout.addWidget(self.loginCustomer)
        self.loginSupplier = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.loginSupplier.setStyleSheet("QPushButton:hover,\n"
"QPushButton:focus {\n"
"    \n"
"  color: rgb(255, 255, 255);\n"
"  background-color: #8360aa;\n"
"  border: 3px solid #8360aa;\n"
"}")
        self.loginSupplier.setObjectName("loginSupplier")
        self.verticalLayout.addWidget(self.loginSupplier)
        self.createAccount = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.createAccount.setStyleSheet("QPushButton:hover,\n"
"QPushButton:focus {\n"
"    \n"
"  color: rgb(255, 255, 255);\n"
"  background-color: #8360aa;\n"
"  border: 3px solid #8360aa;\n"
"}")
        self.createAccount.setObjectName("createAccount")
        self.verticalLayout.addWidget(self.createAccount)
        self.label_12 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(270, 40, 331, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(-20, -10, 911, 711))
        self.label_2.setStyleSheet("QLabel\n"
"QLabel:focus{\n"
"opacity: 0.1\n"
"}\n"
"")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("C:/Users/EAM/Downloads/WhatsApp Image 2023-11-23 at 1.47.19 PM.jpeg"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_2.raise_()
        self.layoutWidget.raise_()
        self.label_12.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 876, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.loginAdmin.setText(_translate("MainWindow", "Log in as Admin"))
        self.loginDistributor.setText(_translate("MainWindow", "Log in as Distributor"))
        self.loginCustomer.setText(_translate("MainWindow", "Log in as Customer"))
        self.loginSupplier.setText(_translate("MainWindow", "Log in as Supplier"))
        self.createAccount.setText(_translate("MainWindow", "Create Account"))
        self.label_12.setText(_translate("MainWindow", "WELCOME TO DAIRYPRO"))
