# Form implementation generated from reading ui file 'c:\Users\hp\Documents\CS_Undergrad\Semester_3\DATABASE\bd_final_project\DairyPro\Code-Connection\Screens\25 Customer Dashboard.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(515, 317)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.productView = QtWidgets.QPushButton(parent=self.centralwidget)
        self.productView.setGeometry(QtCore.QRect(200, 120, 111, 91))
        self.productView.setObjectName("productView")
        self.orders = QtWidgets.QPushButton(parent=self.centralwidget)
        self.orders.setGeometry(QtCore.QRect(50, 120, 111, 91))
        self.orders.setObjectName("orders")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(200, 40, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.customerInfo = QtWidgets.QPushButton(parent=self.centralwidget)
        self.customerInfo.setGeometry(QtCore.QRect(350, 120, 111, 91))
        self.customerInfo.setObjectName("customerInfo")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 515, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.productView.setText(_translate("MainWindow", "Products"))
        self.orders.setText(_translate("MainWindow", "Orders"))
        self.label.setText(_translate("MainWindow", "Customer"))
        self.customerInfo.setText(_translate("MainWindow", "Customer Info"))
