# Form implementation generated from reading ui file 'c:\Users\hp\Documents\CS_Undergrad\Semester_3\DATABASE\bd_final_project\DairyPro\Code-Connection\Screens\3 Login screen.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(421, 366)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(110, 40, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.userId = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.userId.setGeometry(QtCore.QRect(110, 150, 201, 21))
        self.userId.setInputMask("")
        self.userId.setObjectName("userId")
        self.password = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.password.setGeometry(QtCore.QRect(110, 210, 201, 21))
        self.password.setInputMask("")
        self.password.setObjectName("password")
        self.createAccount = QtWidgets.QPushButton(parent=self.centralwidget)
        self.createAccount.setGeometry(QtCore.QRect(80, 250, 121, 31))
        self.createAccount.setObjectName("createAccount")
        self.logInButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.logInButton.setGeometry(QtCore.QRect(220, 250, 121, 31))
        self.logInButton.setObjectName("logInButton")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(110, 130, 55, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(110, 190, 71, 16))
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 421, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Log In"))
        self.userId.setText(_translate("MainWindow", "011245"))
        self.password.setText(_translate("MainWindow", "************"))
        self.createAccount.setText(_translate("MainWindow", "Create Account"))
        self.logInButton.setText(_translate("MainWindow", "Log In"))
        self.label_2.setText(_translate("MainWindow", "User ID:"))
        self.label_3.setText(_translate("MainWindow", "Password:"))
