# Form implementation generated from reading ui file 'c:\Users\hp\Documents\CS_Undergrad\Semester_3\DATABASE\bd_final_project\DairyPro\Code-Connection\Screens\4 Admin dashboard.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(518, 448)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(170, 20, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.productView = QtWidgets.QPushButton(parent=self.centralwidget)
        self.productView.setGeometry(QtCore.QRect(70, 80, 111, 91))
        self.productView.setObjectName("productView")
        self.distributorView = QtWidgets.QPushButton(parent=self.centralwidget)
        self.distributorView.setGeometry(QtCore.QRect(200, 190, 111, 91))
        self.distributorView.setObjectName("distributorView")
        self.inventoryView = QtWidgets.QPushButton(parent=self.centralwidget)
        self.inventoryView.setGeometry(QtCore.QRect(200, 80, 111, 91))
        self.inventoryView.setObjectName("inventoryView")
        self.currentOrders = QtWidgets.QPushButton(parent=self.centralwidget)
        self.currentOrders.setGeometry(QtCore.QRect(70, 190, 111, 91))
        self.currentOrders.setObjectName("currentOrders")
        self.manufactureView = QtWidgets.QPushButton(parent=self.centralwidget)
        self.manufactureView.setGeometry(QtCore.QRect(330, 190, 111, 91))
        self.manufactureView.setObjectName("manufactureView")
        self.rawmatView = QtWidgets.QPushButton(parent=self.centralwidget)
        self.rawmatView.setGeometry(QtCore.QRect(330, 80, 111, 91))
        self.rawmatView.setObjectName("rawmatView")
        self.supplierView = QtWidgets.QPushButton(parent=self.centralwidget)
        self.supplierView.setGeometry(QtCore.QRect(70, 300, 111, 91))
        self.supplierView.setObjectName("supplierView")
        self.customerView = QtWidgets.QPushButton(parent=self.centralwidget)
        self.customerView.setGeometry(QtCore.QRect(200, 300, 111, 91))
        self.customerView.setObjectName("customerView")
        self.exitDatabase = QtWidgets.QPushButton(parent=self.centralwidget)
        self.exitDatabase.setGeometry(QtCore.QRect(330, 300, 111, 91))
        self.exitDatabase.setObjectName("exitDatabase")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 518, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Administration"))
        self.productView.setText(_translate("MainWindow", "Products"))
        self.distributorView.setText(_translate("MainWindow", "Distributors"))
        self.inventoryView.setText(_translate("MainWindow", "Inventory"))
        self.currentOrders.setText(_translate("MainWindow", "Orders"))
        self.manufactureView.setText(_translate("MainWindow", "Manufacturing"))
        self.rawmatView.setText(_translate("MainWindow", "Raw Materials"))
        self.supplierView.setText(_translate("MainWindow", "Supplier"))
        self.customerView.setText(_translate("MainWindow", "Customers"))
        self.exitDatabase.setText(_translate("MainWindow", "Exit Database"))
