# Form implementation generated from reading ui file 'c:\Users\hp\Documents\CS_Undergrad\Semester_3\DATABASE\bd_final_project\DairyPro\DB_ConnectionsFiles\DB_project\23 Customer Button.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(521, 569)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.searched = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.searched.setGeometry(QtCore.QRect(30, 20, 461, 171))
        self.searched.setStyleSheet("font: 8pt \"Comic Sans MS\";\n"
"color: rgb(0, 0, 127);\n"
"")
        self.searched.setObjectName("searched")
        self.searchButton = QtWidgets.QPushButton(parent=self.searched)
        self.searchButton.setGeometry(QtCore.QRect(310, 130, 121, 31))
        self.searchButton.setStyleSheet("background-color: rgb(174, 209, 255);\n"
"font: 10pt \"Comic Sans MS\";\n"
"color: #00007f;\n"
"border-style: outset;\n"
"border-width: 3px;\n"
"border-radius: 5px;\n"
"border-color: #00007f;\n"
"")
        self.searchButton.setObjectName("searchButton")
        self.layoutWidget = QtWidgets.QWidget(parent=self.searched)
        self.layoutWidget.setGeometry(QtCore.QRect(150, 30, 281, 82))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.categoryCombo = QtWidgets.QComboBox(parent=self.layoutWidget)
        self.categoryCombo.setStyleSheet("background-color: rgb(169, 192, 255);\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 5px;\n"
"border-color: #00007f;")
        self.categoryCombo.setObjectName("categoryCombo")
        self.categoryCombo.addItem("")
        self.categoryCombo.addItem("")
        self.categoryCombo.addItem("")
        self.categoryCombo.addItem("")
        self.verticalLayout.addWidget(self.categoryCombo)
        self.titleline = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.titleline.setStyleSheet("background-color: rgb(169, 192, 255);\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 5px;\n"
"border-color: #00007f;")
        self.titleline.setObjectName("titleline")
        self.verticalLayout.addWidget(self.titleline)
        self.layoutWidget1 = QtWidgets.QWidget(parent=self.searched)
        self.layoutWidget1.setGeometry(QtCore.QRect(30, 30, 103, 81))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(parent=self.layoutWidget1)
        self.label.setStyleSheet("font: 8pt \"Comic Sans MS\";")
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(parent=self.layoutWidget1)
        self.label_2.setStyleSheet("font: 8pt \"Comic Sans MS\";")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.booksTableWidget = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.booksTableWidget.setGeometry(QtCore.QRect(30, 220, 461, 191))
        self.booksTableWidget.setStyleSheet("QTableWidget {\n"
"    background-color: rgb(169, 192, 255);\n"
"   alternate-background-color: #e0e0e0;\n"
"   selection-background-color: #4CAF50;\n"
"    border:  rgb(0, 0, 127);; /* Border color around the table */\n"
"    margin: 5px; /* Set the margin size */\n"
"    font: 8pt \"Comic Sans MS\";\n"
"    color: rgb(0, 0, 127);\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    font: 8pt \"Comic Sans MS\";\n"
"    color: rgb(0, 0, 127);\n"
"    \n"
"}\n"
"\n"
"\n"
"QHeaderView::section {\n"
"    background-color:  rgb(169, 192, 255); /* Header background color */\n"
"    color: rgb(0, 0, 127); /* Header text color */\n"
"    padding: 4px; /* Header padding */\n"
"    font: 8pt \"Comic Sans MS\";\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"    background-color: rgb(0, 0, 127) /* Background color for selected items */\n"
"    color: white; /* Text color for selected items */\n"
"}\n"
"")
        self.booksTableWidget.setObjectName("booksTableWidget")
        self.booksTableWidget.setColumnCount(6)
        self.booksTableWidget.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.booksTableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.booksTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.booksTableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.booksTableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.booksTableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.booksTableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.booksTableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.booksTableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.booksTableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.booksTableWidget.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.booksTableWidget.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.booksTableWidget.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.booksTableWidget.setItem(0, 5, item)
        self.viewButton_4 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.viewButton_4.setGeometry(QtCore.QRect(240, 440, 121, 31))
        self.viewButton_4.setStyleSheet("background-color: rgb(174, 209, 255);\n"
"font: 10pt \"Comic Sans MS\";\n"
"color: #00007f;\n"
"border-style: outset;\n"
"border-width: 3px;\n"
"border-radius: 5px;\n"
"border-color: #00007f;\n"
"")
        self.viewButton_4.setObjectName("viewButton_4")
        self.closeButton_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.closeButton_2.setGeometry(QtCore.QRect(370, 480, 121, 31))
        self.closeButton_2.setStyleSheet("background-color: rgb(174, 209, 255);\n"
"font: 10pt \"Comic Sans MS\";\n"
"color: #00007f;\n"
"border-style: outset;\n"
"border-width: 3px;\n"
"border-radius: 5px;\n"
"border-color: #00007f;\n"
"")
        self.closeButton_2.setObjectName("closeButton_2")
        self.deleteButton_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.deleteButton_2.setGeometry(QtCore.QRect(370, 440, 121, 31))
        self.deleteButton_2.setStyleSheet("background-color: rgb(174, 209, 255);\n"
"font: 10pt \"Comic Sans MS\";\n"
"color: #00007f;\n"
"border-style: outset;\n"
"border-width: 3px;\n"
"border-radius: 5px;\n"
"border-color: #00007f;\n"
"")
        self.deleteButton_2.setObjectName("deleteButton_2")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(-10, -20, 961, 681))
        self.label_4.setAutoFillBackground(False)
        self.label_4.setStyleSheet("\n"
"\n"
"background-color: rgb(207, 232, 255);\n"
"")
        self.label_4.setFrameShape(QtWidgets.QFrame.Shape.Panel)
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_4.raise_()
        self.searched.raise_()
        self.booksTableWidget.raise_()
        self.viewButton_4.raise_()
        self.closeButton_2.raise_()
        self.deleteButton_2.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 521, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.searched.setTitle(_translate("MainWindow", "Search"))
        self.searchButton.setText(_translate("MainWindow", "Search"))
        self.categoryCombo.setItemText(0, _translate("MainWindow", "Ahmed"))
        self.categoryCombo.setItemText(1, _translate("MainWindow", "Hamza"))
        self.categoryCombo.setItemText(2, _translate("MainWindow", "Yasir"))
        self.categoryCombo.setItemText(3, _translate("MainWindow", "Majeed"))
        self.titleline.setText(_translate("MainWindow", "011224"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#00007f;\">Customer Name:</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#00007f;\">Customer ID:</span></p></body></html>"))
        item = self.booksTableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.booksTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.booksTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name"))
        item = self.booksTableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Address"))
        item = self.booksTableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Phone number"))
        item = self.booksTableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Email"))
        item = self.booksTableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Activity status"))
        __sortingEnabled = self.booksTableWidget.isSortingEnabled()
        self.booksTableWidget.setSortingEnabled(False)
        item = self.booksTableWidget.item(0, 0)
        item.setText(_translate("MainWindow", "011224"))
        item = self.booksTableWidget.item(0, 1)
        item.setText(_translate("MainWindow", "Ahmed"))
        item = self.booksTableWidget.item(0, 2)
        item.setText(_translate("MainWindow", "222-A, XYZ Street, Gulshan-e-Iqbal"))
        item = self.booksTableWidget.item(0, 3)
        item.setText(_translate("MainWindow", "0324-546765"))
        item = self.booksTableWidget.item(0, 4)
        item.setText(_translate("MainWindow", "ahmed@gmail.com"))
        item = self.booksTableWidget.item(0, 5)
        item.setText(_translate("MainWindow", "Active"))
        self.booksTableWidget.setSortingEnabled(__sortingEnabled)
        self.viewButton_4.setText(_translate("MainWindow", "View"))
        self.closeButton_2.setText(_translate("MainWindow", "Close"))
        self.deleteButton_2.setText(_translate("MainWindow", "Remove"))
