# Form implementation generated from reading ui file 'c:\Users\hp\Documents\CS_Undergrad\Semester_3\DATABASE\bd_final_project\DairyPro\DB_ConnectionsFiles\DB_project\32 distributor dashboard.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(539, 281)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(200, 20, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.distributorView = QtWidgets.QPushButton(parent=self.centralwidget)
        self.distributorView.setGeometry(QtCore.QRect(340, 100, 111, 91))
        self.distributorView.setObjectName("distributorView")
        self.d_orderView = QtWidgets.QPushButton(parent=self.centralwidget)
        self.d_orderView.setGeometry(QtCore.QRect(80, 100, 111, 91))
        self.d_orderView.setObjectName("d_orderView")
        self.prodView = QtWidgets.QPushButton(parent=self.centralwidget)
        self.prodView.setGeometry(QtCore.QRect(210, 100, 111, 91))
        self.prodView.setObjectName("prodView")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 539, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Distributor"))
        self.distributorView.setText(_translate("MainWindow", "Distributor Info"))
        self.d_orderView.setText(_translate("MainWindow", "Orders"))
        self.prodView.setText(_translate("MainWindow", "Products"))
