# Form implementation generated from reading ui file 'c:\Users\hp\Documents\CS_Undergrad\Semester_3\DATABASE\bd_final_project\DairyPro\DB_ConnectionsFiles\DB_project\41 Supplier View Order Form.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(490, 419)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(150, 40, 281, 261))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.mat_id = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.mat_id.setObjectName("mat_id")
        self.verticalLayout.addWidget(self.mat_id)
        self.mat_name = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.mat_name.setObjectName("mat_name")
        self.verticalLayout.addWidget(self.mat_name)
        self.sup_id = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.sup_id.setObjectName("sup_id")
        self.verticalLayout.addWidget(self.sup_id)
        self.cost_line = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.cost_line.setObjectName("cost_line")
        self.verticalLayout.addWidget(self.cost_line)
        self.inven_levl = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.inven_levl.setObjectName("inven_levl")
        self.verticalLayout.addWidget(self.inven_levl)
        self.layoutWidget1 = QtWidgets.QWidget(parent=self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(50, 50, 92, 241))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(parent=self.layoutWidget1)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(parent=self.layoutWidget1)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.label_5 = QtWidgets.QLabel(parent=self.layoutWidget1)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.label_7 = QtWidgets.QLabel(parent=self.layoutWidget1)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_2.addWidget(self.label_7)
        self.label_3 = QtWidgets.QLabel(parent=self.layoutWidget1)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.closeButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.closeButton.setGeometry(QtCore.QRect(310, 320, 121, 31))
        self.closeButton.setObjectName("closeButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 490, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.mat_id.setText(_translate("MainWindow", "56"))
        self.mat_name.setText(_translate("MainWindow", "1001"))
        self.sup_id.setText(_translate("MainWindow", "112244"))
        self.cost_line.setText(_translate("MainWindow", "112244"))
        self.inven_levl.setText(_translate("MainWindow", "500"))
        self.label.setText(_translate("MainWindow", "Material ID:"))
        self.label_2.setText(_translate("MainWindow", "Material Name:"))
        self.label_5.setText(_translate("MainWindow", "Supplier ID:"))
        self.label_7.setText(_translate("MainWindow", "Cost"))
        self.label_3.setText(_translate("MainWindow", "Inventory Level"))
        self.closeButton.setText(_translate("MainWindow", "Close"))
