# Form implementation generated from reading ui file 'c:\Users\hp\Documents\CS_Undergrad\Semester_3\DATABASE\bd_final_project\DairyPro\DB_ConnectionsFiles\DB_project\44 Admin Order Approave.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.adminOrdertable = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.adminOrdertable.setGeometry(QtCore.QRect(180, 80, 441, 192))
        self.adminOrdertable.setStyleSheet("column-width: 130px")
        self.adminOrdertable.setObjectName("adminOrdertable")
        self.adminOrdertable.setColumnCount(4)
        self.adminOrdertable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.adminOrdertable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.adminOrdertable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.adminOrdertable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.adminOrdertable.setHorizontalHeaderItem(3, item)
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(380, 30, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.adminAddOrder = QtWidgets.QPushButton(parent=self.centralwidget)
        self.adminAddOrder.setGeometry(QtCore.QRect(400, 310, 101, 31))
        self.adminAddOrder.setObjectName("adminAddOrder")
        self.closeButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.closeButton.setGeometry(QtCore.QRect(520, 310, 101, 31))
        self.closeButton.setObjectName("closeButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        item = self.adminOrdertable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Order ID"))
        item = self.adminOrdertable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Customer ID"))
        item = self.adminOrdertable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Order Date"))
        item = self.adminOrdertable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Expected delivery"))
        self.label.setText(_translate("MainWindow", "Orders"))
        self.adminAddOrder.setText(_translate("MainWindow", "Approave Order"))
        self.closeButton.setText(_translate("MainWindow", "Close"))
