# Form implementation generated from reading ui file 'c:\Users\hp\Documents\CS_Undergrad\Semester_3\DATABASE\bd_final_project\DairyPro\DB_ConnectionsFiles\DB_project\mani_placd order.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 525)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(-70, -60, 931, 781))
        self.label_4.setAutoFillBackground(False)
        self.label_4.setStyleSheet("\n"
"\n"
"background-color: rgb(207, 232, 255);\n"
"")
        self.label_4.setFrameShape(QtWidgets.QFrame.Shape.Panel)
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_12 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(180, 20, 371, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(16)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("")
        self.label_12.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(130, 80, 231, 40))
        self.label_2.setStyleSheet("font: 10pt \"Comic Sans MS\";\n"
"font-color: rgb(0, 0, 127);")
        self.label_2.setObjectName("label_2")
        self.booksTableWidget = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.booksTableWidget.setGeometry(QtCore.QRect(120, 110, 381, 192))
        self.booksTableWidget.setStyleSheet("QTableWidget {\n"
"    background-color: rgb(169, 192, 255);\n"
"   alternate-background-color: #e0e0e0;\n"
"   selection-background-color: #4CAF50;\n"
"border-color: #00007f;\n"
"    border:  rgb(0, 0, 127);; /* Border color around the table */\n"
"    margin: 5px; /* Set the margin size */\n"
"    font: 8pt \"Comic Sans MS\";\n"
"    color: rgb(0, 0, 127);\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    font: 8pt \"Comic Sans MS\";\n"
"    color: rgb(0, 0, 127);\n"
"    \n"
"}\n"
"\n"
"\n"
"QHeaderView::section {\n"
"    background-color:  rgb(169, 192, 255); /* Header background color */\n"
"    color: rgb(0, 0, 127); /* Header text color */\n"
"    padding: 4px; /* Header padding */\n"
"    font: 8pt \"Comic Sans MS\";\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"    background-color: rgb(0, 0, 127) /* Background color for selected items */\n"
"    color: white; /* Text color for selected items */\n"
"}\n"
"")
        self.booksTableWidget.setObjectName("booksTableWidget")
        self.booksTableWidget.setColumnCount(5)
        self.booksTableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.booksTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.booksTableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.booksTableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.booksTableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.booksTableWidget.setHorizontalHeaderItem(4, item)
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(510, 70, 181, 221))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("c:\\Users\\hp\\Documents\\CS_Undergrad\\Semester_3\\DATABASE\\bd_final_project\\DairyPro\\DB_ConnectionsFiles\\DB_project\\factory.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(200, 300, 231, 40))
        self.label_3.setStyleSheet("font: 10pt \"Comic Sans MS\";\n"
"font-color: rgb(0, 0, 127);")
        self.label_3.setObjectName("label_3")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(380, 310, 113, 20))
        self.lineEdit.setStyleSheet("background-color: rgb(169, 192, 255);\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 5px;\n"
"border-color: #00007f;")
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(340, 340, 151, 21))
        self.pushButton.setStyleSheet("background-color: rgb(174, 209, 255);\n"
"font: 10pt \"Comic Sans MS\";\n"
"color: #00007f;\n"
"border-style: outset;\n"
"border-width: 3px;\n"
"border-radius: 5px;\n"
"border-color: #00007f;\n"
"")
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_12.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#00007f;\">Place Order For the Product</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#00007f;\">Products with Low Inventory Levels</span></p></body></html>"))
        item = self.booksTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Product ID"))
        item = self.booksTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Product Name"))
        item = self.booksTableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Category  ID"))
        item = self.booksTableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Price"))
        item = self.booksTableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Inventory Level"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#00007f;\">Enter Quantity to be manifactured</span></p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "Initiate Manifacturing"))
